version: '3.8'

services:
  db:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://root:admin@db:27017/voting-security?authSource=admin
      # NFT_STORAGE_API_TOKEN: your_api_token_here
      NODE_ENV: production
    volumes:
      - ./backups:/app/backups
      - ./logs:/app/logs
    networks:
      - app_network

volumes:
  mongo_data:
networks:
  app_network:
