services:
  db:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backups:/app/backups
      - ./logs:/app/logs
      - ./temp:/app/temp
    networks:
      - app_network

volumes:
  mongo_data:


networks:
  app_network:
    driver: bridge
